### ISSUE TITLE
Added a test model to install instructions

### ISSUE THREAD

**Issue by gregbritten** [jpmattern/bayesian_cbiomes#2]
After installation I figured everyone should try running a model to make sure everything is installed correctly. Would you mind taking a quick peek before I send it around to the group?

**Comment by jpmattern** [comment]
Yes, let me see if I can figure it out and it all makes sense.

**Comment by jpmattern** [comment]
An `import pystan` was missing in all python models and I fixed that. The only issue is with the Julia model. Printing the fit results in output like:
```
Tuple{String,String}[("/tmp/jl_bM8FGU/mod_chain_1.csv", "/tmp/jl_bM8FGU/mod_chain_1.log"), ("/tmp/jl_bM8FGU/mod_chain_2.csv", "/tmp/jl_bM8FGU/mod_chain_2.log"), ("/tmp/jl_bM8FGU/mod_chain_3.csv", "/tmp/jl_bM8FGU/mod_chain_3.log"), ("/tmp/jl_bM8FGU/mod_chain_4.csv", "/tmp/jl_bM8FGU/mod_chain_4.log")]
```
And those files contain the information from each chain, let me see if there's a better way.

**Comment by jpmattern** [comment]
OK, the solution is a 
```
println(read_summary(mod_compile));
```
which I added to all models. I think we are good to go.
